telegram:
  bot_token: ""  # Можно оставить пустым для MTProto
  api_id: "ВАШ_API_ID"        # Ваш API ID из my.telegram.org
  api_hash: "ВАШ_API_HASH"    # Ваш API Hash из my.telegram.org
  channels:
    - "channel_name_1"         # Имена каналов без @ (например: "trading_signals")
    - "channel_name_2"         # Добавьте каналы, которые хотите анализировать
  start_date: "2024-01-01" # Дата, с которой начинать загрузку сообщений (YYYY-MM-DD)

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "ВАШ_ПАРОЛЬ_БД"
  dbname: "tg_reader"
  sslmode: "disable"


